---@module 'language.translate.markdown.anchors'
---@brief Keeps in-page links (`#slug`) working after the headings were translated.
---@description
--- A link target `#entwurf` points at a heading by its slug. Translate the
--- heading and the slug changes while the (masked, never translated) target
--- does not: spike 2026-10-06, 16 of 18 table-of-contents links broke. The map
--- built here takes the slug of the i-th original heading to the slug of the
--- i-th translated heading and rewrites the targets; a target that matches no
--- heading stays as it is.
---
--- `slug` is the one the mdview client resolves an anchor with
--- (`slugify` in `linkHover.ts`: lower case, anything but letters, digits,
--- white space and hyphens removed, white space to hyphens), letter for letter: the
--- Unicode classes come from `unicode.lua`. The first heading with a slug wins, as it
--- does in the client; a repeated slug is numbered `-1`, `-2` ... the way GitHub and
--- markdown.nvim number it, so a table of contents generated by the latter maps too.

local M = {}

local unicode = require("language.translate.markdown.unicode")

---@internal
---Lower case like `String.prototype.toLowerCase`: `vim.fn.tolower` agrees with it
---for every code point but a capital sigma that ends a word (a cased letter before it,
---none behind it, marks and apostrophes skipped), which is `ς`: the `Cased` and
---`Case_Ignorable` classes of `unicode.lua` decide that (checked against the JS function
---over ~800 000 strings).
---@param s string
---@return string
local function lower(s)
  if not s:find("[\128-\255]") then
    return s:lower()
  end
  if s:find("\206\163", 1, true) then
    local chars = {}
    for ch, cp in unicode.chars(s) do
      chars[#chars + 1] = { ch, cp }
    end
    -- Final_Sigma (Unicode SpecialCasing, what `toLowerCase` applies): a cased letter
    -- before (case-ignorable marks, apostrophes ... skipped) and none behind.
    ---@param from integer
    ---@param step integer
    ---@return boolean
    local function cased_beyond(from, step)
      local j = from
      while chars[j] and unicode.is_case_ignorable(chars[j][2]) do
        j = j + step
      end
      return chars[j] ~= nil and unicode.is_cased(chars[j][2])
    end
    for i, c in ipairs(chars) do
      if c[2] == 0x3A3 and cased_beyond(i - 1, -1) and not cased_beyond(i + 1, 1) then
        c[1] = "\207\130"
      end
    end
    for i, c in ipairs(chars) do
      chars[i] = c[1]
    end
    s = table.concat(chars)
  end
  local ok, res = pcall(vim.fn.tolower, s)
  return ok and type(res) == "string" and res or s:lower()
end

---Slug of a heading text (plain text, no Markdown).
---@param text string
---@return string
function M.slug(text)
  -- `vim.fn.tolower` turns a string with a NUL into a Blob; the byte is dropped below
  -- anyway, as any control character is, so another one stands in for it.
  text = (text:gsub("%z", "\1"))
  if text:find("[\128-\255]") then
    -- Bytes that are no UTF-8 would be read as Latin-1 by `tolower`; a decoder drops them.
    local valid = {}
    for ch, cp in unicode.chars(text) do
      if cp ~= 0xFFFD or ch == "\239\191\189" then
        valid[#valid + 1] = ch
      end
    end
    text = table.concat(valid)
  end
  text = lower(text)
  -- White space becomes one hyphen between two kept characters (none at the edges),
  -- decided on the way: trimming a long run afterwards with `" +$"` is quadratic.
  local parts, n = {}, 0
  local gap = false
  for ch, cp in unicode.chars(text) do
    local keep, space = nil, false
    if cp < 128 then
      if ch:match("[%w-]") then
        keep = ch
      elseif ch:match("%s") then
        space = true
      end
    elseif unicode.is_space(cp) then
      space = true
    elseif unicode.is_alnum(cp) then
      keep = ch
    end
    if space then
      gap = n > 0
    elseif keep then
      if gap then
        n = n + 1
        parts[n] = "-"
        gap = false
      end
      n = n + 1
      parts[n] = keep
    end
  end
  return (table.concat(parts):gsub("%-+", "-"))
end

---@internal
---Decode the character references a heading can carry (the previewer slugs the
---rendered text, where `&auml;` is `ä`).
---@param s string
---@return string
local function decode_entities(s)
  if not s:find("&", 1, true) then
    return s
  end
  local NAMED = {
    amp = "&",
    lt = "<",
    gt = ">",
    quot = '"',
    apos = "'",
    nbsp = "\194\160",
    auml = "ä",
    ouml = "ö",
    uuml = "ü",
    Auml = "Ä",
    Ouml = "Ö",
    Uuml = "Ü",
    szlig = "ß",
    eacute = "é",
    egrave = "è",
    agrave = "à",
    aacute = "á",
    ccedil = "ç",
    ntilde = "ñ",
  }
  s = s:gsub("&#[xX](%x+);", function(h)
    local cp = tonumber(h, 16)
    return cp and cp > 0 and cp <= 0x10FFFF and vim.fn.nr2char(cp) or nil
  end)
  s = s:gsub("&#(%d+);", function(d)
    local cp = tonumber(d)
    return cp and cp > 0 and cp <= 0x10FFFF and vim.fn.nr2char(cp) or nil
  end)
  s = s:gsub("&(%a+);", function(name)
    return NAMED[name]
  end)
  return s
end

---Plain text of a Markdown heading, as the previewer's `textContent` sees it:
---link text stays, an image contributes nothing (its alt text is no text node),
---code ticks, HTML tags and emphasis markers are dropped, an autolink shows its
---address, character references are decoded.
---@param md string
---@return string
function M.plain(md)
  local s = md
  -- The link patterns retry from every `[`, to the end of the text when no `]` follows:
  -- a long heading with many brackets is left alone (its anchor stays as it is).
  local _, brackets = s:gsub("%[", "")
  if #s * brackets <= 4000000 then
    s = s:gsub("!%[[^%]]*%]%b()", "")
    s = s:gsub("!%[[^%]]*%]%[[^%]]*%]", "")
    s = s:gsub("%[([^%]]*)%]%b()", "%1")
    s = s:gsub("%[([^%]]*)%]%[[^%]]*%]", "%1")
  end
  s = s:gsub("<(%a[%w+.-]*:[^%s<>]*)>", "%1")
  s = s:gsub("<[^<>]*>", "")
  s = s:gsub("`", "")
  s = s:gsub("%*", "")
  return decode_entities(s)
end

---Map the slug of each original heading to the slug of its translation. A
---repeated slug is numbered the way GitHub and markdown.nvim number it
---(`intro`, `intro-1`, `intro-2`), on both sides.
---@param old string[]  -- original heading texts (Markdown)
---@param new string[]  -- translated heading texts, same order
---@return table<string, string> map, integer changed
function M.build_map(old, new)
  local map, changed = {}, 0
  local seen_old, seen_new = {}, {}
  ---@param seen table<string, integer>
  ---@param slug string
  ---@return string
  local function numbered(seen, slug)
    local c = seen[slug] or 0
    seen[slug] = c + 1
    return c == 0 and slug or (slug .. "-" .. c)
  end
  for i = 1, #old do
    local a = M.slug(M.plain(old[i]))
    local b = new[i] and M.slug(M.plain(new[i])) or ""
    if a ~= "" and b ~= "" then
      local ka, kb = numbered(seen_old, a), numbered(seen_new, b)
      if map[ka] == nil then
        map[ka] = kb
        if ka ~= kb then
          changed = changed + 1
        end
      end
    elseif a ~= "" then
      numbered(seen_old, a)
    end
  end
  return map, changed
end

---@internal
---@param s string
---@return string
local function pct_decode(s)
  return (s:gsub("%%(%x%x)", function(h)
    return string.char(tonumber(h, 16))
  end))
end

---Rewrite the destination of a masked link half (`](#slug "title")`).
---@param text string
---@param map table<string, string>
---@return string text, boolean changed
function M.rewrite_dest(text, map)
  local head, slug, tail = text:match("^(%]%(<?)#([^%s>)\"']*)(.*)$")
  if not head then
    return text, false
  end
  local new = map[M.slug(pct_decode(slug))]
  if not new or new == slug then
    return text, false
  end
  return head .. "#" .. new .. tail, true
end

---Rewrite the target of a reference definition line (`[x]: #slug`).
---@param line string
---@param map table<string, string>
---@return string line, boolean changed
function M.rewrite_refdef(line, map)
  local head, slug, tail = line:match("^(%s*%[[^%]]+%]:%s*<?)#([^%s>]*)(.*)$")
  if not head then
    return line, false
  end
  local new = map[M.slug(pct_decode(slug))]
  if not new or new == slug then
    return line, false
  end
  return head .. "#" .. new .. tail, true
end

return M
